/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_iso.View;

import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.xml.bind.Marshaller;
import proyecto_iso.Base.Conexion;
import proyecto_iso.Mensaje;

import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.border.Border;
import javax.swing.border.SoftBevelBorder;
import proyecto_iso.Insercion;
import proyecto_iso.InsercionTablas;
import proyecto_iso.Modificacion;
import proyecto_iso.Validaciones;
import proyecto_iso.ValidarSoporte;

/**
 *
 * @author FZ1891
 */
public class Ingreso_View extends javax.swing.JFrame {

    /**
     * Creates new form Ingreso_View
     */
    DefaultTableModel dtm = new DefaultTableModel();
    JLabel[] btMenu = new JLabel[5];
    //Problema p = new Problema(this);
    Border bordePanelbtn = new SoftBevelBorder(1, Color.BLACK, Color.DARK_GRAY);
//    DefaultTableModel dtmSubject = new DefaultTableModel();
    Validaciones validar = new Validaciones();
    boolean isModify=false;
    Modificacion modify;
    InsercionTablas ingresoProblem;
    public Ingreso_View() {

        initComponents();
       // txtPromeblaModificar.setLineWrap(true);
//        dtmSubject.addColumn("N°");
//        dtmSubject.addColumn("Problema");
//        this.setLocationRelativeTo(null);
//        tbProblemasSubject.setModel(dtmSubject);
        pnFather.removeAll();
        pnFather.repaint();
        pnFather.revalidate();
        pnFather.add(pnSoporteMainMenu);
        pnFather.repaint();
        pnFather.revalidate();
        IngresoPanel();
        this.setLocationRelativeTo(null); 
        tbProblemasSubject.setRowHeight(50);
        tbProblemasSubject.setFont(new java.awt.Font("Tahoma", 0, 20));
        lbNewTema.setEnabled(false);

    }

    public void llenar_tabla_Menu(String sql) {
//        try
//        {
//          Connection conex=Conexion.conexion();
//          Statement st=conex.createStatement();
//          ResultSet rs=st.executeQuery(sql);
//          ResultSetMetaData rsmt =rs.getMetaData();
//          int CantCol=rsmt.getColumnCount();
//          Object[] llenar=new Object[CantCol+2];        
//            while(rs.next())
//            {             
//             for (int i = 0; i < CantCol+2; i++)
//               {
//                if(i<=1)
//                {
//                  llenar[i]=rs.getObject(i+1);
//                }
//                else if(i==2)
//                {
//                                 
//                  bt1.addActionListener(new ActionListener() {
//
//                      @Override
//                      public void actionPerformed(ActionEvent e) {
//                          JOptionPane.showMessageDialog(null,"Hello"); 
//                      }
//                  });
//                  llenar[i]=bt1;                             
//                }
//                else
//                { 
//                bt2.addActionListener(new ActionListener() {
//                      @Override
//                      public void actionPerformed(ActionEvent e) {
//                        JOptionPane.showMessageDialog(null,"Hello"); 
//                      }
//                  });
//                llenar[i]=bt2;  
//                }
//                       
//               }
//              dtm.addRow(llenar);  
//             }     
//        }
//        catch(SQLException sex)
//        {
//            JOptionPane.showMessageDialog(null,sex.toString());
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnFather = new javax.swing.JPanel();
        pnSoporteMainMenu = new javax.swing.JPanel();
        rSPanelGradiente1 = new rspanelgradiente.RSPanelGradiente();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        pnNewSubjectBtn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnModifyBtn = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        pnElinimarBtn = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        pnExitBtn = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        pnConsultaBtn = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        Intro = new javax.swing.JPanel();
        pnNewSubject = new javax.swing.JPanel();
        pnNewSubjectCard = new javax.swing.JPanel();
        pnNewSubjectList = new javax.swing.JPanel();
        btOk = new javax.swing.JButton();
        lbAplicacion = new javax.swing.JLabel();
        lbErrorAlLlenar = new javax.swing.JLabel();
        txtTema = new javax.swing.JTextField();
        lbServicio = new javax.swing.JLabel();
        txtAplicacion = new javax.swing.JTextField();
        lbTema = new javax.swing.JLabel();
        txtServicio = new javax.swing.JTextField();
        lbTema1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        btnHability = new javax.swing.JButton();
        pnInsertar = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbProblemasSubject = new javax.swing.JTable();
        lbBtnMasSolcion = new javax.swing.JLabel();
        lbBtnMasProblema = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbSolucionSubject = new javax.swing.JTable();
        lbBtnGuardar = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbSolucionPerfect = new javax.swing.JTable();
        lbBtnMasSolucionPerfect = new javax.swing.JLabel();
        lbNewTema = new javax.swing.JLabel();
        lbDatosTema = new javax.swing.JLabel();
        lbReturn = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbService = new javax.swing.JLabel();
        lbAplication = new javax.swing.JLabel();
        pnModify = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtBuscar = new javax.swing.JTextField();
        lbBuscar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbModify = new javax.swing.JTable();
        cbBusquedaPor = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnModificacion = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtNumIndextb = new javax.swing.JTextField();
        pnDelete = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnFather.setBackground(new java.awt.Color(153, 153, 153));
        pnFather.setPreferredSize(new java.awt.Dimension(1110, 650));
        pnFather.setLayout(new java.awt.CardLayout());

        pnSoporteMainMenu.setBackground(new java.awt.Color(255, 255, 255));
        pnSoporteMainMenu.setMaximumSize(new java.awt.Dimension(1110, 650));
        pnSoporteMainMenu.setMinimumSize(new java.awt.Dimension(1110, 650));
        pnSoporteMainMenu.setName(""); // NOI18N
        pnSoporteMainMenu.setPreferredSize(new java.awt.Dimension(1110, 650));

        rSPanelGradiente1.setColorPrimario(new java.awt.Color(51, 204, 255));
        rSPanelGradiente1.setColorSecundario(new java.awt.Color(51, 0, 153));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/MIsIcons/info.png"))); // NOI18N

        jLabel18.setBackground(new java.awt.Color(51, 51, 51));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/folder/Icons@1x-assets/App/AppIcons_4.png"))); // NOI18N
        jLabel18.setMaximumSize(new java.awt.Dimension(200, 200));
        jLabel18.setMinimumSize(new java.awt.Dimension(200, 200));
        jLabel18.setOpaque(true);
        jLabel18.setPreferredSize(new java.awt.Dimension(200, 200));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel4.setText("SOPORTE");

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jSeparator2.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout rSPanelGradiente1Layout = new javax.swing.GroupLayout(rSPanelGradiente1);
        rSPanelGradiente1.setLayout(rSPanelGradiente1Layout);
        rSPanelGradiente1Layout.setHorizontalGroup(
            rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelGradiente1Layout.createSequentialGroup()
                .addContainerGap(254, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addContainerGap())
            .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                    .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                            .addGap(92, 92, 92)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                            .addGap(48, 48, 48)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addComponent(jLabel4)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        rSPanelGradiente1Layout.setVerticalGroup(
            rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelGradiente1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                    .addGap(134, 134, 134)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(52, 52, 52)
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(195, Short.MAX_VALUE)))
        );

        pnNewSubjectBtn.setBackground(new java.awt.Color(255, 255, 255));
        pnNewSubjectBtn.setOpaque(false);
        pnNewSubjectBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnNewSubjectBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnNewSubjectBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnNewSubjectBtnMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/MIsIcons/anadir-pagina.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nuevo Tema");
        jLabel3.setOpaque(true);

        javax.swing.GroupLayout pnNewSubjectBtnLayout = new javax.swing.GroupLayout(pnNewSubjectBtn);
        pnNewSubjectBtn.setLayout(pnNewSubjectBtnLayout);
        pnNewSubjectBtnLayout.setHorizontalGroup(
            pnNewSubjectBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        pnNewSubjectBtnLayout.setVerticalGroup(
            pnNewSubjectBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnNewSubjectBtnLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnModifyBtn.setBackground(new java.awt.Color(255, 255, 255));
        pnModifyBtn.setOpaque(false);
        pnModifyBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnModifyBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnModifyBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnModifyBtnMouseExited(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/MIsIcons/actualizar.png"))); // NOI18N
        jLabel20.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 24)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Modificar");
        jLabel21.setOpaque(true);

        javax.swing.GroupLayout pnModifyBtnLayout = new javax.swing.GroupLayout(pnModifyBtn);
        pnModifyBtn.setLayout(pnModifyBtnLayout);
        pnModifyBtnLayout.setHorizontalGroup(
            pnModifyBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnModifyBtnLayout.setVerticalGroup(
            pnModifyBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnModifyBtnLayout.createSequentialGroup()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnElinimarBtn.setBackground(new java.awt.Color(255, 255, 255));
        pnElinimarBtn.setOpaque(false);
        pnElinimarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnElinimarBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnElinimarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnElinimarBtnMouseExited(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/MIsIcons/archivo.png"))); // NOI18N
        jLabel22.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 24)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText(" Eliminar");
        jLabel23.setOpaque(true);

        javax.swing.GroupLayout pnElinimarBtnLayout = new javax.swing.GroupLayout(pnElinimarBtn);
        pnElinimarBtn.setLayout(pnElinimarBtnLayout);
        pnElinimarBtnLayout.setHorizontalGroup(
            pnElinimarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnElinimarBtnLayout.setVerticalGroup(
            pnElinimarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnElinimarBtnLayout.createSequentialGroup()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnExitBtn.setBackground(new java.awt.Color(255, 255, 255));
        pnExitBtn.setOpaque(false);
        pnExitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnExitBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnExitBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnExitBtnMouseExited(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/MIsIcons/salida.png"))); // NOI18N
        jLabel24.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 24)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Salir");
        jLabel25.setOpaque(true);

        javax.swing.GroupLayout pnExitBtnLayout = new javax.swing.GroupLayout(pnExitBtn);
        pnExitBtn.setLayout(pnExitBtnLayout);
        pnExitBtnLayout.setHorizontalGroup(
            pnExitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnExitBtnLayout.setVerticalGroup(
            pnExitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnExitBtnLayout.createSequentialGroup()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnConsultaBtn.setBackground(new java.awt.Color(255, 255, 255));
        pnConsultaBtn.setOpaque(false);
        pnConsultaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnConsultaBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnConsultaBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnConsultaBtnMouseExited(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/MIsIcons/archivolook.png"))); // NOI18N
        jLabel26.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 24)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText(" Consultar");
        jLabel27.setOpaque(true);

        javax.swing.GroupLayout pnConsultaBtnLayout = new javax.swing.GroupLayout(pnConsultaBtn);
        pnConsultaBtn.setLayout(pnConsultaBtnLayout);
        pnConsultaBtnLayout.setHorizontalGroup(
            pnConsultaBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnConsultaBtnLayout.setVerticalGroup(
            pnConsultaBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnConsultaBtnLayout.createSequentialGroup()
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pnSoporteMainMenuLayout = new javax.swing.GroupLayout(pnSoporteMainMenu);
        pnSoporteMainMenu.setLayout(pnSoporteMainMenuLayout);
        pnSoporteMainMenuLayout.setHorizontalGroup(
            pnSoporteMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSoporteMainMenuLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pnSoporteMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnSoporteMainMenuLayout.createSequentialGroup()
                        .addComponent(pnNewSubjectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(pnModifyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(pnElinimarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnSoporteMainMenuLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(pnConsultaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(pnExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(rSPanelGradiente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnSoporteMainMenuLayout.setVerticalGroup(
            pnSoporteMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSoporteMainMenuLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(pnSoporteMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnNewSubjectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnModifyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnElinimarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnSoporteMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnConsultaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 78, Short.MAX_VALUE))
            .addComponent(rSPanelGradiente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnFather.add(pnSoporteMainMenu, "card2");

        Intro.setLayout(new java.awt.CardLayout());

        pnNewSubject.setBackground(new java.awt.Color(51, 51, 51));
        pnNewSubject.setMinimumSize(new java.awt.Dimension(1110, 650));
        pnNewSubject.setPreferredSize(new java.awt.Dimension(1110, 650));
        pnNewSubject.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnNewSubjectCard.setBackground(new java.awt.Color(102, 102, 102));
        pnNewSubjectCard.setLayout(new java.awt.CardLayout());

        pnNewSubjectList.setBackground(new java.awt.Color(255, 255, 255));
        pnNewSubjectList.setMinimumSize(new java.awt.Dimension(1110, 650));
        pnNewSubjectList.setPreferredSize(new java.awt.Dimension(1110, 650));

        btOk.setText("Ok");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        lbAplicacion.setFont(new java.awt.Font("Calibri Light", 0, 36)); // NOI18N
        lbAplicacion.setLabelFor(txtAplicacion);
        lbAplicacion.setText("Aplicación :");

        lbErrorAlLlenar.setForeground(new java.awt.Color(204, 0, 0));
        lbErrorAlLlenar.setText("Todos los datos deben ser llenados");

        txtTema.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtTema.setBorder(null);
        txtTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTemaActionPerformed(evt);
            }
        });

        lbServicio.setFont(new java.awt.Font("Calibri Light", 0, 36)); // NOI18N
        lbServicio.setLabelFor(txtServicio);
        lbServicio.setText("Servicio :");

        txtAplicacion.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtAplicacion.setBorder(null);
        txtAplicacion.setOpaque(false);
        txtAplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAplicacionActionPerformed(evt);
            }
        });

        lbTema.setFont(new java.awt.Font("Calibri Light", 0, 36)); // NOI18N
        lbTema.setLabelFor(txtTema);
        lbTema.setText("Tema :");

        txtServicio.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtServicio.setBorder(null);
        txtServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServicioActionPerformed(evt);
            }
        });

        lbTema1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbTema1.setLabelFor(txtTema);
        lbTema1.setText("Descipción del tema :");

        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtDescripcion.setRows(5);
        jScrollPane4.setViewportView(txtDescripcion);

        jButton2.setText("Cancelar");
        jButton2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton2FocusGained(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOpaque(true);

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator4.setOpaque(true);

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator5.setOpaque(true);

        btnHability.setText("Habilitar");

        javax.swing.GroupLayout pnNewSubjectListLayout = new javax.swing.GroupLayout(pnNewSubjectList);
        pnNewSubjectList.setLayout(pnNewSubjectListLayout);
        pnNewSubjectListLayout.setHorizontalGroup(
            pnNewSubjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNewSubjectListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnNewSubjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnNewSubjectListLayout.createSequentialGroup()
                        .addComponent(lbErrorAlLlenar, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 439, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnNewSubjectListLayout.createSequentialGroup()
                        .addGroup(pnNewSubjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbAplicacion)
                            .addGroup(pnNewSubjectListLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(pnNewSubjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbTema)
                                    .addComponent(lbServicio))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnNewSubjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnNewSubjectListLayout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(137, 137, 137)
                                .addComponent(btOk, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnNewSubjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTema, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                                .addComponent(txtServicio, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                                .addComponent(txtAplicacion, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                                .addComponent(jSeparator3)
                                .addComponent(jSeparator4)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(pnNewSubjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnNewSubjectListLayout.createSequentialGroup()
                        .addGroup(pnNewSubjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTema1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnNewSubjectListLayout.createSequentialGroup()
                        .addComponent(btnHability)
                        .addGap(73, 73, 73))))
        );
        pnNewSubjectListLayout.setVerticalGroup(
            pnNewSubjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNewSubjectListLayout.createSequentialGroup()
                .addGroup(pnNewSubjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnNewSubjectListLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(pnNewSubjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbTema1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnNewSubjectListLayout.createSequentialGroup()
                                .addGroup(pnNewSubjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTema, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbTema, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)))
                        .addGap(22, 22, 22)
                        .addGroup(pnNewSubjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(pnNewSubjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbAplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addGroup(pnNewSubjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btOk, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(129, 129, 129))
                    .addGroup(pnNewSubjectListLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(pnNewSubjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbErrorAlLlenar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHability))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pnNewSubjectCard.add(pnNewSubjectList, "card16");

        pnInsertar.setBackground(new java.awt.Color(255, 255, 255));
        pnInsertar.setMinimumSize(new java.awt.Dimension(1110, 650));
        pnInsertar.setPreferredSize(new java.awt.Dimension(1110, 650));

        tbProblemasSubject.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbProblemasSubject.setRowHeight(25);
        tbProblemasSubject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProblemasSubjectMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbProblemasSubject);

        lbBtnMasSolcion.setBackground(new java.awt.Color(255, 255, 255));
        lbBtnMasSolcion.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        lbBtnMasSolcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/MIsIcons/plus.png"))); // NOI18N
        lbBtnMasSolcion.setText(" APLICACION");
        lbBtnMasSolcion.setOpaque(true);

        lbBtnMasProblema.setBackground(new java.awt.Color(255, 255, 255));
        lbBtnMasProblema.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        lbBtnMasProblema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/MIsIcons/plus.png"))); // NOI18N
        lbBtnMasProblema.setText(" PROBLEMA");
        lbBtnMasProblema.setOpaque(true);

        tbSolucionSubject.setRowHeight(25);
        tbSolucionSubject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSolucionSubjectMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbSolucionSubject);

        lbBtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/MIsIcons/guardar.png"))); // NOI18N

        tbSolucionPerfect.setRowHeight(25);
        tbSolucionPerfect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSolucionPerfectMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tbSolucionPerfect);

        lbBtnMasSolucionPerfect.setBackground(new java.awt.Color(255, 255, 255));
        lbBtnMasSolucionPerfect.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        lbBtnMasSolucionPerfect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/MIsIcons/plus.png"))); // NOI18N
        lbBtnMasSolucionPerfect.setText(" SOLUCIONES");
        lbBtnMasSolucionPerfect.setOpaque(true);

        javax.swing.GroupLayout pnInsertarLayout = new javax.swing.GroupLayout(pnInsertar);
        pnInsertar.setLayout(pnInsertarLayout);
        pnInsertarLayout.setHorizontalGroup(
            pnInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnInsertarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbBtnMasProblema))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnInsertarLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnInsertarLayout.createSequentialGroup()
                        .addComponent(lbBtnMasSolcion)
                        .addGap(134, 134, 134)))
                .addGroup(pnInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnInsertarLayout.createSequentialGroup()
                        .addComponent(lbBtnMasSolucionPerfect, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(lbBtnGuardar)))
                .addGap(84, 84, 84))
        );
        pnInsertarLayout.setVerticalGroup(
            pnInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnInsertarLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pnInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbBtnMasProblema, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbBtnMasSolcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbBtnMasSolucionPerfect))
                    .addComponent(lbBtnGuardar))
                .addGap(18, 18, 18)
                .addGroup(pnInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pnNewSubjectCard.add(pnInsertar, "card3");

        pnNewSubject.add(pnNewSubjectCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1110, 570));

        lbNewTema.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbNewTema.setForeground(new java.awt.Color(255, 255, 255));
        lbNewTema.setText("Nuevo Tema");
        lbNewTema.setPreferredSize(new java.awt.Dimension(50, 44));
        lbNewTema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbNewTemaMouseClicked(evt);
            }
        });
        pnNewSubject.add(lbNewTema, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 830, -1));

        lbDatosTema.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbDatosTema.setForeground(new java.awt.Color(255, 255, 255));
        lbDatosTema.setText("Servicio:");
        pnNewSubject.add(lbDatosTema, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 30));

        lbReturn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/MIsIcons/flecha-izquierda2.png"))); // NOI18N
        lbReturn.setAutoscrolls(true);
        lbReturn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbReturnMouseClicked(evt);
            }
        });
        pnNewSubject.add(lbReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 4, 70, 70));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Aplicacion:");
        pnNewSubject.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, -1, 30));

        lbService.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbService.setForeground(new java.awt.Color(255, 255, 255));
        lbService.setText("null");
        pnNewSubject.add(lbService, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 370, 30));

        lbAplication.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbAplication.setForeground(new java.awt.Color(255, 255, 255));
        lbAplication.setText("null");
        pnNewSubject.add(lbAplication, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 310, 30));

        Intro.add(pnNewSubject, "card2");

        pnModify.setBackground(new java.awt.Color(153, 153, 153));
        pnModify.setMinimumSize(new java.awt.Dimension(1110, 650));
        pnModify.setPreferredSize(new java.awt.Dimension(1110, 650));
        pnModify.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setMinimumSize(new java.awt.Dimension(1110, 650));
        jPanel6.setPreferredSize(new java.awt.Dimension(1110, 650));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Modify");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 60));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("Buscar");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel6.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 230, 70));

        txtBuscar.setBorder(null);
        jPanel6.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 230, 20));

        lbBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/MIsIcons/buscar-lupa-simbolo-de-interfaz.png"))); // NOI18N
        jPanel6.add(lbBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 50, -1, -1));

        jScrollPane1.setViewportView(tbModify);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 1080, 350));

        cbBusquedaPor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tema", "Aplicacion", "Servicio", "Problema", "Solucion" }));
        cbBusquedaPor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBusquedaPorActionPerformed(evt);
            }
        });
        jPanel6.add(cbBusquedaPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 220, 30));

        jLabel5.setText("Buesqueda por :");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        jLabel6.setText("Resultados de la busqueda :");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        btnModificacion.setText("Modificar");
        btnModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificacionActionPerformed(evt);
            }
        });
        jPanel6.add(btnModificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 540, -1, -1));

        jLabel7.setText("Seleccione un dato de una celda de la tabla");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 550, 620, -1));

        txtNumIndextb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumIndextbActionPerformed(evt);
            }
        });
        txtNumIndextb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumIndextbKeyPressed(evt);
            }
        });
        jPanel6.add(txtNumIndextb, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, 50, -1));

        pnModify.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 650));

        Intro.add(pnModify, "card3");

        pnDelete.setBackground(new java.awt.Color(153, 153, 153));
        pnDelete.setMaximumSize(new java.awt.Dimension(1110, 650));
        pnDelete.setMinimumSize(new java.awt.Dimension(1110, 650));
        pnDelete.setPreferredSize(new java.awt.Dimension(1110, 650));

        jPanel8.setBackground(new java.awt.Color(153, 153, 153));
        jPanel8.setPreferredSize(new java.awt.Dimension(1110, 650));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTable2);

        jPanel8.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        jPanel9.setBackground(new java.awt.Color(153, 153, 153));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(153, 153, 153));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, 0, 590, 610));

        javax.swing.GroupLayout pnDeleteLayout = new javax.swing.GroupLayout(pnDelete);
        pnDelete.setLayout(pnDeleteLayout);
        pnDeleteLayout.setHorizontalGroup(
            pnDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDeleteLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 1110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 1110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnDeleteLayout.setVerticalGroup(
            pnDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Intro.add(pnDelete, "card4");

        pnFather.add(Intro, "card7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnFather, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnFather, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void txtAplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAplicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAplicacionActionPerformed

    private void txtServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServicioActionPerformed

    private void txtTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTemaActionPerformed

    public void IngresoPanel() {
        Insercion ingreso = new Insercion(txtTema, txtAplicacion, txtServicio
                , txtDescripcion, btOk, pnNewSubjectCard,
                  pnNewSubjectList, pnInsertar,lbService,lbAplication,lbNewTema);
//        Insercion ingresoProblem = new Insercion(btAgregarModificar, btCargarModificar,
//                txtPromeblaModificar, txtSolucion, txtNumColumModificar, dtmSubject,
//                tbProblemasSubject, lbProblemNum, btnGuardar);
         ingresoProblem = new InsercionTablas(this,lbBtnMasProblema,
                lbBtnMasSolcion,tbProblemasSubject, tbSolucionSubject,
                tbSolucionPerfect,lbBtnGuardar,lbService,lbAplication,lbNewTema,lbBtnMasSolucionPerfect);
        
         modify= new Modificacion(tbModify, txtBuscar, lbBuscar, cbBusquedaPor,
                txtTema, txtAplicacion, txtServicio, tbProblemasSubject,
                tbSolucionSubject, pnNewSubject, pnFather,
                pnModify, lbNewTema,btnModificacion,txtNumIndextb,ingresoProblem);
        isModify=ingresoProblem.isModify;

    }

    private void lbReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbReturnMouseClicked
    if(!ingresoProblem.isModify)
      {
        pnFather.removeAll();
        pnFather.repaint();
        pnFather.revalidate();
        pnFather.add(pnSoporteMainMenu);
        pnFather.repaint();
        pnFather.revalidate();
      }
     else
      {
        pnFather.removeAll();
        pnFather.repaint();
        pnFather.revalidate();
        pnFather.add(pnModify);
        pnFather.repaint();
        pnFather.revalidate();
      }
    }//GEN-LAST:event_lbReturnMouseClicked

    
            
       
    private void pnNewSubjectBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnNewSubjectBtnMouseClicked
        ExitObjectPanel(pnNewSubjectBtn);
        pnFather.removeAll();
        pnFather.repaint();
        pnFather.revalidate();
        pnFather.add(pnNewSubject);
        pnFather.repaint();
        pnFather.revalidate();
        pnNewSubjectList.remove(btnHability);
        cleanPanelsSubject();
        
    }//GEN-LAST:event_pnNewSubjectBtnMouseClicked

   void cleanPanelsSubject()
    {
        txtTema.setText(null);
        txtAplicacion.setText(null);
        txtServicio.setText(null);
        lbAplication.setText(null);
        lbService.setText(null);
        lbNewTema.setText("Sin Tema");
        cleanJTableSubject();
    }
   void cleanJTableSubject()
    {
      ingresoProblem.cleanTableSubjectTbProblem();
      ingresoProblem.cleanTableSubjectTbSolution();
      ingresoProblem.isModify=false;
      ingresoProblem.isUpdate=false;
    }
    
    
    
    private void pnNewSubjectBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnNewSubjectBtnMouseEntered

        EnterObjectPanel(pnNewSubjectBtn);
    }//GEN-LAST:event_pnNewSubjectBtnMouseEntered

    private void pnNewSubjectBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnNewSubjectBtnMouseExited

        ExitObjectPanel(pnNewSubjectBtn);
    }//GEN-LAST:event_pnNewSubjectBtnMouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2FocusGained

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    private void pnModifyBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnModifyBtnMouseClicked
        // TODO add your handling code here:
        
        ExitObjectPanel(pnNewSubjectBtn);
        pnFather.removeAll();
        pnFather.repaint();
        pnFather.revalidate();
        pnFather.add(pnModify);
        pnFather.repaint();
        pnFather.revalidate();
        
    }//GEN-LAST:event_pnModifyBtnMouseClicked
   
    private void pnModifyBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnModifyBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnModifyBtnMouseEntered

    private void pnModifyBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnModifyBtnMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnModifyBtnMouseExited

    private void pnElinimarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnElinimarBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnElinimarBtnMouseClicked

    private void pnElinimarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnElinimarBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnElinimarBtnMouseEntered

    private void pnElinimarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnElinimarBtnMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnElinimarBtnMouseExited

    private void pnExitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnExitBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnExitBtnMouseClicked

    private void pnExitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnExitBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnExitBtnMouseEntered

    private void pnExitBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnExitBtnMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnExitBtnMouseExited

    private void pnConsultaBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnConsultaBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnConsultaBtnMouseClicked

    private void pnConsultaBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnConsultaBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnConsultaBtnMouseEntered

    private void pnConsultaBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnConsultaBtnMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnConsultaBtnMouseExited

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked

        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel24MouseClicked

    private void cbBusquedaPorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBusquedaPorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbBusquedaPorActionPerformed

    private void btnModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificacionActionPerformed

//        int numIndex = Integer.parseInt(txtNumIndextb.getText());
        

    }//GEN-LAST:event_btnModificacionActionPerformed

    private void txtNumIndextbKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumIndextbKeyPressed

        //  validar.validarTxtField(txtNumIndextb);
        validar.ValidarsoloNUmeros(txtNumIndextb);
    }//GEN-LAST:event_txtNumIndextbKeyPressed

    private void tbProblemasSubjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProblemasSubjectMouseClicked

        int rowSelectTable = tbModify.getSelectedRow() + 1;
        String rowSelectTable_ = String.valueOf(rowSelectTable);
        txtNumIndextb.setText(rowSelectTable_);
    }//GEN-LAST:event_tbProblemasSubjectMouseClicked
   
    private void tbSolucionSubjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSolucionSubjectMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbSolucionSubjectMouseClicked

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btOkActionPerformed

    private void lbNewTemaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNewTemaMouseClicked
        // TODO add your handling code here:
        pnNewSubjectCard.removeAll();
        pnNewSubjectCard.repaint();
        pnNewSubjectCard.revalidate();
        pnNewSubjectCard.add(pnNewSubjectList);
        pnNewSubjectCard.repaint();
        pnNewSubjectCard.revalidate();
        lbNewTema.setEnabled(false);
        pnNewSubjectList.remove(btnHability);
    }//GEN-LAST:event_lbNewTemaMouseClicked

    private void txtNumIndextbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumIndextbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumIndextbActionPerformed

    private void tbSolucionPerfectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSolucionPerfectMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbSolucionPerfectMouseClicked

    public void añadirProblema(String problem) {


    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingreso_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingreso_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingreso_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingreso_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingreso_View().setVisible(true);
            }
        });
    }

    private void EnterObjectPanel(JPanel p) {
        //p.setBackground( new Color(153,153,255));
        p.setBorder(bordePanelbtn);

    }

    private void ExitObjectPanel(JPanel p) {
        //  p.setBackground( new Color(255,255,255));
        p.setBorder(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Intro;
    private javax.swing.JButton btOk;
    private javax.swing.JButton btnHability;
    private javax.swing.JButton btnModificacion;
    private javax.swing.JComboBox<String> cbBusquedaPor;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lbAplicacion;
    private javax.swing.JLabel lbAplication;
    private javax.swing.JLabel lbBtnGuardar;
    private javax.swing.JLabel lbBtnMasProblema;
    private javax.swing.JLabel lbBtnMasSolcion;
    private javax.swing.JLabel lbBtnMasSolucionPerfect;
    private javax.swing.JLabel lbBuscar;
    private javax.swing.JLabel lbDatosTema;
    private javax.swing.JLabel lbErrorAlLlenar;
    private javax.swing.JLabel lbNewTema;
    private javax.swing.JLabel lbReturn;
    private javax.swing.JLabel lbService;
    private javax.swing.JLabel lbServicio;
    private javax.swing.JLabel lbTema;
    private javax.swing.JLabel lbTema1;
    private javax.swing.JPanel pnConsultaBtn;
    private javax.swing.JPanel pnDelete;
    private javax.swing.JPanel pnElinimarBtn;
    private javax.swing.JPanel pnExitBtn;
    private javax.swing.JPanel pnFather;
    private javax.swing.JPanel pnInsertar;
    private javax.swing.JPanel pnModify;
    private javax.swing.JPanel pnModifyBtn;
    private javax.swing.JPanel pnNewSubject;
    private javax.swing.JPanel pnNewSubjectBtn;
    private javax.swing.JPanel pnNewSubjectCard;
    private javax.swing.JPanel pnNewSubjectList;
    private javax.swing.JPanel pnSoporteMainMenu;
    private rspanelgradiente.RSPanelGradiente rSPanelGradiente1;
    private javax.swing.JTable tbModify;
    private javax.swing.JTable tbProblemasSubject;
    private javax.swing.JTable tbSolucionPerfect;
    private javax.swing.JTable tbSolucionSubject;
    private javax.swing.JTextField txtAplicacion;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtNumIndextb;
    private javax.swing.JTextField txtServicio;
    private javax.swing.JTextField txtTema;
    // End of variables declaration//GEN-END:variables
}
