/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_iso.View;

import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.xml.bind.Marshaller;
import proyecto_iso.Base.Conexion;


import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.border.Border;
import javax.swing.border.SoftBevelBorder;
import proyecto_iso.Insercion;
import proyecto_iso.InsercionTablas;
import proyecto_iso.Modificacion;

import proyecto_iso.Validaciones;


/**
 *
 * @author FZ1891
 */
public class Ingreso_View extends javax.swing.JFrame {

    /**
     * Creates new form Ingreso_View
     */
    DefaultTableModel dtm = new DefaultTableModel();
    JLabel[] btMenu = new JLabel[5];
    //Problema p = new Problema(this);
    Border bordePanelbtn = new SoftBevelBorder(1, Color.BLACK, Color.DARK_GRAY);
//    DefaultTableModel dtmSubject = new DefaultTableModel();
    Validaciones validar = new Validaciones();
    boolean isModify=false;
    Modificacion modify;
    InsercionTablas ingresoProblem;
    public Ingreso_View() {

        initComponents();
//        Section
//          estas lineas de codigo nos permite que solo nos aparezca el menu 
//          y no los otros paneles
        pnFather.removeAll();
        pnFather.repaint();
        pnFather.revalidate();
        pnFather.add(pnSoporteMainMenu);
        pnFather.repaint();
        pnFather.revalidate();
//        end Section

//        este metodo instacia las clases Ingreso, ingresoTablas , modificacion
//         cada una de estas clases controla un panel especifico
//           ingreso-pnNewSubjectList
//           ingresoTablas-pnInsertar
//           modificacion-pnModificacion
        IngresoPanel();
//        coloca en el centro del la pantalla
        this.setLocationRelativeTo(null); 
        
        lbIsModify.setVisible(false);
     //   tbProblemasSubject.setRowHeight(50);
     //   tbProblemasSubject.setFont(new java.awt.Font("Tahoma", 0, 20));
        lbNewTema.setEnabled(false);
        //this.remove(jmMeniMain);
    }

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnFather = new javax.swing.JPanel();
        pnSoporteMainMenu = new javax.swing.JPanel();
        rSPanelGradiente1 = new rspanelgradiente.RSPanelGradiente();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        pnNewSubjectBtn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnModifyBtn = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        pnElinimarBtn = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        pnExitBtn = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        Intro = new javax.swing.JPanel();
        pnNewSubject = new javax.swing.JPanel();
        pnNewSubjectCard = new javax.swing.JPanel();
        pnNewSubjectList = new javax.swing.JPanel();
        btOk = new javax.swing.JButton();
        lbAplicacion = new javax.swing.JLabel();
        lbErrorAlLlenar = new javax.swing.JLabel();
        txtTema = new javax.swing.JTextField();
        lbServicio = new javax.swing.JLabel();
        txtAplicacion = new javax.swing.JTextField();
        lbTema = new javax.swing.JLabel();
        txtServicio = new javax.swing.JTextField();
        lbTema1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaDescription = new javax.swing.JTextArea();
        pnInsertar = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbProblemasSubject = new javax.swing.JTable();
        lbBtnMasSolcion = new javax.swing.JLabel();
        lbBtnMasProblema = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbSolucionSubject = new javax.swing.JTable();
        lbBtnGuardar = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbSolucionPerfect = new javax.swing.JTable();
        lbBtnMasSolucionPerfect = new javax.swing.JLabel();
        lbNewTema = new javax.swing.JLabel();
        lbDatosTema = new javax.swing.JLabel();
        lbReturn = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbService = new javax.swing.JLabel();
        lbAplication = new javax.swing.JLabel();
        lbIsModify = new javax.swing.JLabel();
        pnModify = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lbNamePanelForThree = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtBuscar = new javax.swing.JTextField();
        lbBuscar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbModify = new javax.swing.JTable();
        cbBusquedaPor = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnModificacion = new javax.swing.JButton();
        lbPrecautionModify = new javax.swing.JLabel();
        txtNumIndextb = new javax.swing.JTextField();
        btnVer = new javax.swing.JButton();
        btnGeneratePdf = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        pnDelete = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        pnConsultar = new javax.swing.JPanel();
        jmMeniMain = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        menuOpcNuevo = new javax.swing.JMenu();
        menuOpcModificar = new javax.swing.JMenu();
        menuOpcEliminar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnFather.setBackground(new java.awt.Color(153, 153, 153));
        pnFather.setPreferredSize(new java.awt.Dimension(1110, 650));
        pnFather.setLayout(new java.awt.CardLayout());

        pnSoporteMainMenu.setBackground(new java.awt.Color(255, 255, 255));
        pnSoporteMainMenu.setMaximumSize(new java.awt.Dimension(1110, 650));
        pnSoporteMainMenu.setMinimumSize(new java.awt.Dimension(1110, 650));
        pnSoporteMainMenu.setName(""); // NOI18N
        pnSoporteMainMenu.setPreferredSize(new java.awt.Dimension(1110, 650));

        rSPanelGradiente1.setColorPrimario(new java.awt.Color(51, 204, 255));
        rSPanelGradiente1.setColorSecundario(new java.awt.Color(51, 0, 153));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/MIsIcons/info.png"))); // NOI18N

        jLabel18.setBackground(new java.awt.Color(51, 51, 51));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/folder/Icons@1x-assets/App/AppIcons_4.png"))); // NOI18N
        jLabel18.setMaximumSize(new java.awt.Dimension(200, 200));
        jLabel18.setMinimumSize(new java.awt.Dimension(200, 200));
        jLabel18.setOpaque(true);
        jLabel18.setPreferredSize(new java.awt.Dimension(200, 200));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel4.setText("SOPORTE");

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jSeparator2.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout rSPanelGradiente1Layout = new javax.swing.GroupLayout(rSPanelGradiente1);
        rSPanelGradiente1.setLayout(rSPanelGradiente1Layout);
        rSPanelGradiente1Layout.setHorizontalGroup(
            rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelGradiente1Layout.createSequentialGroup()
                .addContainerGap(254, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addContainerGap())
            .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                    .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                            .addGap(92, 92, 92)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                            .addGap(48, 48, 48)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addComponent(jLabel4)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        rSPanelGradiente1Layout.setVerticalGroup(
            rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelGradiente1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                    .addGap(134, 134, 134)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(52, 52, 52)
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(195, Short.MAX_VALUE)))
        );

        pnNewSubjectBtn.setBackground(new java.awt.Color(255, 255, 255));
        pnNewSubjectBtn.setOpaque(false);
        pnNewSubjectBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnNewSubjectBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnNewSubjectBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnNewSubjectBtnMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/MIsIcons/anadir-pagina.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nuevo Tema");
        jLabel3.setOpaque(true);

        javax.swing.GroupLayout pnNewSubjectBtnLayout = new javax.swing.GroupLayout(pnNewSubjectBtn);
        pnNewSubjectBtn.setLayout(pnNewSubjectBtnLayout);
        pnNewSubjectBtnLayout.setHorizontalGroup(
            pnNewSubjectBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        pnNewSubjectBtnLayout.setVerticalGroup(
            pnNewSubjectBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnNewSubjectBtnLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnModifyBtn.setBackground(new java.awt.Color(255, 255, 255));
        pnModifyBtn.setOpaque(false);
        pnModifyBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnModifyBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnModifyBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnModifyBtnMouseExited(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/MIsIcons/actualizar.png"))); // NOI18N
        jLabel20.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 24)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Modificar");
        jLabel21.setOpaque(true);

        javax.swing.GroupLayout pnModifyBtnLayout = new javax.swing.GroupLayout(pnModifyBtn);
        pnModifyBtn.setLayout(pnModifyBtnLayout);
        pnModifyBtnLayout.setHorizontalGroup(
            pnModifyBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnModifyBtnLayout.setVerticalGroup(
            pnModifyBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnModifyBtnLayout.createSequentialGroup()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnElinimarBtn.setBackground(new java.awt.Color(255, 255, 255));
        pnElinimarBtn.setOpaque(false);
        pnElinimarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnElinimarBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnElinimarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnElinimarBtnMouseExited(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/MIsIcons/archivo.png"))); // NOI18N
        jLabel22.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 24)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText(" Eliminar");
        jLabel23.setOpaque(true);

        javax.swing.GroupLayout pnElinimarBtnLayout = new javax.swing.GroupLayout(pnElinimarBtn);
        pnElinimarBtn.setLayout(pnElinimarBtnLayout);
        pnElinimarBtnLayout.setHorizontalGroup(
            pnElinimarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnElinimarBtnLayout.setVerticalGroup(
            pnElinimarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnElinimarBtnLayout.createSequentialGroup()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnExitBtn.setBackground(new java.awt.Color(255, 255, 255));
        pnExitBtn.setOpaque(false);
        pnExitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnExitBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnExitBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnExitBtnMouseExited(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/MIsIcons/salida.png"))); // NOI18N
        jLabel24.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 24)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Salir");
        jLabel25.setOpaque(true);

        javax.swing.GroupLayout pnExitBtnLayout = new javax.swing.GroupLayout(pnExitBtn);
        pnExitBtn.setLayout(pnExitBtnLayout);
        pnExitBtnLayout.setHorizontalGroup(
            pnExitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnExitBtnLayout.setVerticalGroup(
            pnExitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnExitBtnLayout.createSequentialGroup()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pnSoporteMainMenuLayout = new javax.swing.GroupLayout(pnSoporteMainMenu);
        pnSoporteMainMenu.setLayout(pnSoporteMainMenuLayout);
        pnSoporteMainMenuLayout.setHorizontalGroup(
            pnSoporteMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSoporteMainMenuLayout.createSequentialGroup()
                .addGroup(pnSoporteMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnSoporteMainMenuLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(pnNewSubjectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(pnModifyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(pnElinimarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnSoporteMainMenuLayout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(pnExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(rSPanelGradiente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnSoporteMainMenuLayout.setVerticalGroup(
            pnSoporteMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSoporteMainMenuLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(pnSoporteMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnNewSubjectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnModifyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnElinimarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(pnExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 78, Short.MAX_VALUE))
            .addComponent(rSPanelGradiente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnFather.add(pnSoporteMainMenu, "card2");

        Intro.setLayout(new java.awt.CardLayout());

        pnNewSubject.setBackground(new java.awt.Color(51, 51, 51));
        pnNewSubject.setMinimumSize(new java.awt.Dimension(1110, 650));
        pnNewSubject.setPreferredSize(new java.awt.Dimension(1110, 650));
        pnNewSubject.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnNewSubjectCard.setBackground(new java.awt.Color(102, 102, 102));
        pnNewSubjectCard.setLayout(new java.awt.CardLayout());

        pnNewSubjectList.setBackground(new java.awt.Color(255, 255, 255));
        pnNewSubjectList.setMinimumSize(new java.awt.Dimension(1110, 650));
        pnNewSubjectList.setPreferredSize(new java.awt.Dimension(1110, 650));
        pnNewSubjectList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btOk.setText("Ok");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });
        pnNewSubjectList.add(btOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 316, 135, 40));

        lbAplicacion.setFont(new java.awt.Font("Calibri Light", 0, 36)); // NOI18N
        lbAplicacion.setLabelFor(txtAplicacion);
        lbAplicacion.setText("Aplicación :");
        pnNewSubjectList.add(lbAplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 227, -1, 52));

        lbErrorAlLlenar.setForeground(new java.awt.Color(204, 0, 0));
        lbErrorAlLlenar.setText("Todos los datos deben ser llenados");
        pnNewSubjectList.add(lbErrorAlLlenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 512, 260, 38));

        txtTema.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtTema.setBorder(null);
        txtTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTemaActionPerformed(evt);
            }
        });
        pnNewSubjectList.add(txtTema, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 448, 30));

        lbServicio.setFont(new java.awt.Font("Calibri Light", 0, 36)); // NOI18N
        lbServicio.setLabelFor(txtServicio);
        lbServicio.setText("Servicio :");
        pnNewSubjectList.add(lbServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 151, -1, 40));

        txtAplicacion.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtAplicacion.setBorder(null);
        txtAplicacion.setOpaque(false);
        txtAplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAplicacionActionPerformed(evt);
            }
        });
        pnNewSubjectList.add(txtAplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 448, 34));

        lbTema.setFont(new java.awt.Font("Calibri Light", 0, 36)); // NOI18N
        lbTema.setLabelFor(txtTema);
        lbTema.setText("Tema :");
        pnNewSubjectList.add(lbTema, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 65, -1, 46));

        txtServicio.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtServicio.setBorder(null);
        txtServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServicioActionPerformed(evt);
            }
        });
        pnNewSubjectList.add(txtServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 448, 36));

        lbTema1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbTema1.setLabelFor(txtTema);
        lbTema1.setText("Descipción del tema :");
        pnNewSubjectList.add(lbTema1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 70, 238, 46));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOpaque(true);
        pnNewSubjectList.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 448, 10));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator4.setOpaque(true);
        pnNewSubjectList.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 448, 10));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator5.setOpaque(true);
        pnNewSubjectList.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 448, 10));

        txtaDescription.setColumns(20);
        txtaDescription.setRows(5);
        jScrollPane2.setViewportView(txtaDescription);

        pnNewSubjectList.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, 330, 140));

        pnNewSubjectCard.add(pnNewSubjectList, "card16");

        pnInsertar.setBackground(new java.awt.Color(255, 255, 255));
        pnInsertar.setMinimumSize(new java.awt.Dimension(1110, 650));
        pnInsertar.setPreferredSize(new java.awt.Dimension(1110, 650));

        tbProblemasSubject.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbProblemasSubject.setRowHeight(25);
        tbProblemasSubject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProblemasSubjectMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbProblemasSubject);

        lbBtnMasSolcion.setBackground(new java.awt.Color(255, 255, 255));
        lbBtnMasSolcion.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        lbBtnMasSolcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/MIsIcons/plus.png"))); // NOI18N
        lbBtnMasSolcion.setText(" APLICACION");
        lbBtnMasSolcion.setOpaque(true);

        lbBtnMasProblema.setBackground(new java.awt.Color(255, 255, 255));
        lbBtnMasProblema.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        lbBtnMasProblema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/MIsIcons/plus.png"))); // NOI18N
        lbBtnMasProblema.setText(" PROBLEMA");
        lbBtnMasProblema.setOpaque(true);

        tbSolucionSubject.setRowHeight(25);
        tbSolucionSubject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSolucionSubjectMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbSolucionSubject);

        lbBtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/MIsIcons/guardar.png"))); // NOI18N

        tbSolucionPerfect.setRowHeight(25);
        tbSolucionPerfect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSolucionPerfectMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tbSolucionPerfect);

        lbBtnMasSolucionPerfect.setBackground(new java.awt.Color(255, 255, 255));
        lbBtnMasSolucionPerfect.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        lbBtnMasSolucionPerfect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/MIsIcons/plus.png"))); // NOI18N
        lbBtnMasSolucionPerfect.setText(" SOLUCIONES");
        lbBtnMasSolucionPerfect.setOpaque(true);

        javax.swing.GroupLayout pnInsertarLayout = new javax.swing.GroupLayout(pnInsertar);
        pnInsertar.setLayout(pnInsertarLayout);
        pnInsertarLayout.setHorizontalGroup(
            pnInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnInsertarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbBtnMasProblema))
                .addGroup(pnInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnInsertarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(lbBtnMasSolcion)
                        .addGap(134, 134, 134)
                        .addComponent(lbBtnMasSolucionPerfect, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(lbBtnGuardar))
                    .addGroup(pnInsertarLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );
        pnInsertarLayout.setVerticalGroup(
            pnInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnInsertarLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pnInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbBtnMasProblema, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbBtnMasSolcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbBtnMasSolucionPerfect))
                    .addComponent(lbBtnGuardar))
                .addGap(18, 18, 18)
                .addGroup(pnInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pnNewSubjectCard.add(pnInsertar, "card3");

        pnNewSubject.add(pnNewSubjectCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1110, 570));

        lbNewTema.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbNewTema.setForeground(new java.awt.Color(255, 255, 255));
        lbNewTema.setText("Nuevo Tema");
        lbNewTema.setPreferredSize(new java.awt.Dimension(50, 44));
        lbNewTema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbNewTemaMouseClicked(evt);
            }
        });
        pnNewSubject.add(lbNewTema, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 610, -1));

        lbDatosTema.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbDatosTema.setForeground(new java.awt.Color(255, 255, 255));
        lbDatosTema.setText("Servicio:");
        pnNewSubject.add(lbDatosTema, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 30));

        lbReturn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/MIsIcons/flecha-izquierda2.png"))); // NOI18N
        lbReturn.setAutoscrolls(true);
        lbReturn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbReturnMouseClicked(evt);
            }
        });
        pnNewSubject.add(lbReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, 70, 70));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Aplicacion:");
        pnNewSubject.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, -1, 30));

        lbService.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbService.setForeground(new java.awt.Color(255, 255, 255));
        lbService.setText("null");
        pnNewSubject.add(lbService, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 370, 30));

        lbAplication.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbAplication.setForeground(new java.awt.Color(255, 255, 255));
        lbAplication.setText("null");
        pnNewSubject.add(lbAplication, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 310, 30));

        lbIsModify.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbIsModify.setForeground(new java.awt.Color(204, 0, 102));
        pnNewSubject.add(lbIsModify, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 320, 30));

        Intro.add(pnNewSubject, "card2");

        pnModify.setBackground(new java.awt.Color(153, 153, 153));
        pnModify.setMinimumSize(new java.awt.Dimension(1110, 650));
        pnModify.setPreferredSize(new java.awt.Dimension(1110, 650));
        pnModify.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setMinimumSize(new java.awt.Dimension(1110, 650));
        jPanel6.setPreferredSize(new java.awt.Dimension(1110, 650));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbNamePanelForThree.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbNamePanelForThree.setForeground(new java.awt.Color(51, 51, 51));
        lbNamePanelForThree.setText("Modify");
        jPanel6.add(lbNamePanelForThree, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 590, 60));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("Buscar");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel6.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 270, 70));

        txtBuscar.setBorder(null);
        jPanel6.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 260, 20));

        lbBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/MIsIcons/buscar-lupa-simbolo-de-interfaz.png"))); // NOI18N
        jPanel6.add(lbBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 70, -1, -1));

        jScrollPane1.setViewportView(tbModify);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 1080, 350));

        cbBusquedaPor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tema", "Aplicacion", "Servicio", "Problema", "Solucion" }));
        cbBusquedaPor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBusquedaPorActionPerformed(evt);
            }
        });
        jPanel6.add(cbBusquedaPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 220, 30));

        jLabel5.setText("Buesqueda por :");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        jLabel6.setText("Resultados de la busqueda :");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        btnModificacion.setText("Modificar");
        btnModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificacionActionPerformed(evt);
            }
        });
        jPanel6.add(btnModificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, -1, -1));

        lbPrecautionModify.setText("Seleccione un dato de una celda de la tabla");
        jPanel6.add(lbPrecautionModify, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 550, 330, -1));

        txtNumIndextb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumIndextbActionPerformed(evt);
            }
        });
        txtNumIndextb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumIndextbKeyPressed(evt);
            }
        });
        jPanel6.add(txtNumIndextb, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, 50, -1));

        btnVer.setText("Ver");
        jPanel6.add(btnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 60, -1));

        btnGeneratePdf.setText("Generar Informe Pdf");
        jPanel6.add(btnGeneratePdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 540, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/MIsIcons/flecha-izquierda.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 20, 40, -1));

        pnModify.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 650));

        Intro.add(pnModify, "card3");

        pnDelete.setBackground(new java.awt.Color(153, 153, 153));
        pnDelete.setMaximumSize(new java.awt.Dimension(1110, 650));
        pnDelete.setMinimumSize(new java.awt.Dimension(1110, 650));
        pnDelete.setPreferredSize(new java.awt.Dimension(1110, 650));

        jPanel8.setBackground(new java.awt.Color(153, 153, 153));
        jPanel8.setPreferredSize(new java.awt.Dimension(1110, 650));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTable2);

        jPanel8.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 710, -1));

        jPanel9.setBackground(new java.awt.Color(153, 153, 153));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(153, 153, 153));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, 0, 590, 610));

        javax.swing.GroupLayout pnDeleteLayout = new javax.swing.GroupLayout(pnDelete);
        pnDelete.setLayout(pnDeleteLayout);
        pnDeleteLayout.setHorizontalGroup(
            pnDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDeleteLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 1110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 1110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnDeleteLayout.setVerticalGroup(
            pnDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Intro.add(pnDelete, "card4");

        pnConsultar.setBackground(new java.awt.Color(153, 153, 153));
        pnConsultar.setMaximumSize(new java.awt.Dimension(1110, 650));
        pnConsultar.setMinimumSize(new java.awt.Dimension(1110, 650));

        javax.swing.GroupLayout pnConsultarLayout = new javax.swing.GroupLayout(pnConsultar);
        pnConsultar.setLayout(pnConsultarLayout);
        pnConsultarLayout.setHorizontalGroup(
            pnConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1110, Short.MAX_VALUE)
        );
        pnConsultarLayout.setVerticalGroup(
            pnConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        Intro.add(pnConsultar, "card4");

        pnFather.add(Intro, "card7");

        jmMeniMain.setBackground(new java.awt.Color(0, 0, 0));
        jmMeniMain.setMinimumSize(new java.awt.Dimension(35, 51));
        jmMeniMain.setPreferredSize(new java.awt.Dimension(76, 40));

        jMenu1.setText("Archivo");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });

        jMenu2.setText("Salir");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenu1.add(jMenu2);

        jmMeniMain.add(jMenu1);

        jMenu3.setText("Opciones");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        menuOpcNuevo.setText("NuevoTema");
        menuOpcNuevo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        menuOpcNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuOpcNuevoMouseClicked(evt);
            }
        });
        menuOpcNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpcNuevoActionPerformed(evt);
            }
        });
        jMenu3.add(menuOpcNuevo);

        menuOpcModificar.setText("Modicar Tema");
        menuOpcModificar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        menuOpcModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuOpcModificarMouseClicked(evt);
            }
        });
        jMenu3.add(menuOpcModificar);

        menuOpcEliminar.setText("Eliminar Tema");
        menuOpcEliminar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        menuOpcEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuOpcEliminarMouseClicked(evt);
            }
        });
        jMenu3.add(menuOpcEliminar);

        jmMeniMain.add(jMenu3);

        setJMenuBar(jmMeniMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnFather, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnFather, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void txtAplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAplicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAplicacionActionPerformed

    private void txtServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServicioActionPerformed

    private void txtTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTemaActionPerformed

    public void IngresoPanel() {
        Insercion ingreso = new Insercion(txtTema, txtAplicacion, txtServicio
                , txtaDescription, btOk, pnNewSubjectCard,
                  pnNewSubjectList, pnInsertar,lbService,lbAplication,lbNewTema);
//        Insercion ingresoProblem = new Insercion(btAgregarModificar, btCargarModificar,
//                txtPromeblaModificar, txtSolucion, txtNumColumModificar, dtmSubject,
//                tbProblemasSubject, lbProblemNum, btnGuardar);
         ingresoProblem = new InsercionTablas(this,lbBtnMasProblema,
                lbBtnMasSolcion,tbProblemasSubject, tbSolucionSubject,
                tbSolucionPerfect,lbBtnGuardar,lbService,lbAplication,lbNewTema,lbBtnMasSolucionPerfect);
        
         modify= new Modificacion(tbModify, txtBuscar, lbBuscar, cbBusquedaPor,
                txtTema, txtAplicacion, txtServicio, tbProblemasSubject,
                tbSolucionSubject, pnNewSubject, pnFather,
                pnModify, lbNewTema,btnModificacion,txtNumIndextb,ingresoProblem
                ,lbNewTema,lbAplication,lbService,pnNewSubjectCard,pnNewSubjectList,pnInsertar,
         lbIsModify,lbNamePanelForThree,btnVer,this,btnGeneratePdf);
        isModify=ingresoProblem.isModify;
    
    }
//    metodo del boton de retroceso al menu principal
    private void lbReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbReturnMouseClicked
    if(!ingresoProblem.isModify)
      {
        pnFather.removeAll();
        pnFather.repaint();
        pnFather.revalidate();
        pnFather.add(pnSoporteMainMenu);
        pnFather.repaint();
        pnFather.revalidate();
      }
     else
      {
        pnFather.removeAll();
        pnFather.repaint();
        pnFather.revalidate();
        pnFather.add(pnModify);
        pnFather.repaint();
        pnFather.revalidate();
      }
    }//GEN-LAST:event_lbReturnMouseClicked

    
            
       
    private void pnNewSubjectBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnNewSubjectBtnMouseClicked
  
        goNewSubject();    
    }//GEN-LAST:event_pnNewSubjectBtnMouseClicked

//    metodo que nos muestra el panel newsubject
    void goNewSubject()
    {
        ExitObjectPanel(pnNewSubjectBtn);
        pnFather.removeAll();
        pnFather.repaint();
        pnFather.revalidate();
        pnFather.add(pnNewSubject);
        pnFather.repaint();
        pnFather.revalidate();
       
        pnNewSubjectCard.remove(pnInsertar);
        pnNewSubjectCard.add(pnNewSubjectList);
        cleanPanelsSubject();
        lbIsModify.setVisible(false);
                
    }
//    metodo que nos limpia el panel newSubject
   void cleanPanelsSubject()
    {
        txtTema.setText(null);
        txtAplicacion.setText(null);
        txtServicio.setText(null);
        lbAplication.setText(null);
        lbService.setText(null);
        lbNewTema.setText("Sin Tema");
        cleanJTableSubject();
    }
//   metodo que nos limpia el panel Insertar
   void cleanJTableSubject()
    {
      ingresoProblem.cleanTableSubjectTbProblem();
      ingresoProblem.cleanTableSubjectTbSolution();
      ingresoProblem.isModify=false;
      ingresoProblem.isUpdate=false;
    }
   
   void cleanPanelForThree()
   {
       modify.CleanTbModify();
       txtBuscar.setText(null);
   }
    
    
    private void pnNewSubjectBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnNewSubjectBtnMouseEntered

        EnterObjectPanel(pnNewSubjectBtn);
    }//GEN-LAST:event_pnNewSubjectBtnMouseEntered

    private void pnNewSubjectBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnNewSubjectBtnMouseExited

        ExitObjectPanel(pnNewSubjectBtn);
    }//GEN-LAST:event_pnNewSubjectBtnMouseExited

    private void pnModifyBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnModifyBtnMouseClicked
        // TODO add your handling code here:
        
       goModify();
    }//GEN-LAST:event_pnModifyBtnMouseClicked
//   metodo que nos muestra el panel modificacion
    void goModify()
    {
        ExitObjectPanel(pnNewSubjectBtn);
        pnFather.removeAll();
        pnFather.repaint();
        pnFather.revalidate();
        pnFather.add(pnModify);
        pnFather.repaint();
        pnFather.revalidate();
        lbIsModify.setVisible(true);
        modify.asModify();
        cleanPanelForThree();
        
    }
     void goEliminar()
    {
       // ExitObjectPanel(pnNewSubjectBtn);
        pnFather.removeAll();
        pnFather.repaint();
        pnFather.revalidate();
        pnFather.add(pnModify);
        pnFather.repaint();
        pnFather.revalidate();
        lbIsModify.setVisible(true);
        
        modify.asEliminacion();
        cleanPanelForThree();    
    }
    private void pnModifyBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnModifyBtnMouseEntered
        // TODO add your handling code here:
        EnterObjectPanel(pnModifyBtn);
    }//GEN-LAST:event_pnModifyBtnMouseEntered

    private void pnModifyBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnModifyBtnMouseExited
        // TODO add your handling code here:
        ExitObjectPanel(pnModifyBtn);
    }//GEN-LAST:event_pnModifyBtnMouseExited

    private void pnElinimarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnElinimarBtnMouseClicked
 
       goEliminar();
    }//GEN-LAST:event_pnElinimarBtnMouseClicked

    private void pnElinimarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnElinimarBtnMouseEntered
        // TODO add your handling code here:
        EnterObjectPanel(pnElinimarBtn);
    }//GEN-LAST:event_pnElinimarBtnMouseEntered

    private void pnElinimarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnElinimarBtnMouseExited
        // TODO add your handling code here:
        ExitObjectPanel(pnElinimarBtn);
    }//GEN-LAST:event_pnElinimarBtnMouseExited

    private void pnExitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnExitBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnExitBtnMouseClicked

    private void pnExitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnExitBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnExitBtnMouseEntered

    private void pnExitBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnExitBtnMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnExitBtnMouseExited
//    metodo para salir del programa
    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked

        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel24MouseClicked

    private void cbBusquedaPorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBusquedaPorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbBusquedaPorActionPerformed

    private void btnModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificacionActionPerformed

//        int numIndex = Integer.parseInt(txtNumIndextb.getText());
        

    }//GEN-LAST:event_btnModificacionActionPerformed

    private void txtNumIndextbKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumIndextbKeyPressed

        //  validar.validarTxtField(txtNumIndextb);
        validar.ValidarsoloNUmeros(txtNumIndextb);
    }//GEN-LAST:event_txtNumIndextbKeyPressed

    private void tbProblemasSubjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProblemasSubjectMouseClicked

        int rowSelectTable = tbModify.getSelectedRow() + 1;
        String rowSelectTable_ = String.valueOf(rowSelectTable);
        txtNumIndextb.setText(rowSelectTable_);
    }//GEN-LAST:event_tbProblemasSubjectMouseClicked
   
    private void tbSolucionSubjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSolucionSubjectMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbSolucionSubjectMouseClicked

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btOkActionPerformed
//    metodo que nos retorna del panel insertar al newSubject
    private void lbNewTemaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNewTemaMouseClicked
        // TODO add your handling code here:
        pnNewSubjectCard.removeAll();
        pnNewSubjectCard.repaint();
        pnNewSubjectCard.revalidate();
        pnNewSubjectCard.add(pnNewSubjectList);
        pnNewSubjectCard.repaint();
        pnNewSubjectCard.revalidate();
        lbNewTema.setEnabled(false);
        
    }//GEN-LAST:event_lbNewTemaMouseClicked

    
    private void txtNumIndextbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumIndextbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumIndextbActionPerformed

    private void tbSolucionPerfectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSolucionPerfectMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbSolucionPerfectMouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void menuOpcNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpcNuevoActionPerformed
        // TODO add your handling code here:
//        JOptionPane.showMessageDialog(null,"Hola");
//        goNewSubject();   
    }//GEN-LAST:event_menuOpcNuevoActionPerformed

    private void menuOpcNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuOpcNuevoMouseClicked
        // TODO add your handling code here:
          int opc=0;
       if(ingresoProblem.isModify)
       {
         opc=JOptionPane.showConfirmDialog(null, "Perdera los datos cargados, ir?", "Confirmar salida", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);     
       }
       if(opc==0) goNewSubject(); 
    }//GEN-LAST:event_menuOpcNuevoMouseClicked

    private void menuOpcModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuOpcModificarMouseClicked
        // TODO add your handling code here:
      int opc=0;
       if(ingresoProblem.isModify)
       {
         opc=JOptionPane.showConfirmDialog(null, "Perdera los datos cargados, ir?", "Confirmar salida", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);       
       }
       if(opc==0) goModify();
       
    }//GEN-LAST:event_menuOpcModificarMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        pnFather.removeAll();
        pnFather.repaint();
        pnFather.revalidate();
        pnFather.add(pnSoporteMainMenu);
        pnFather.repaint();
        pnFather.revalidate();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void menuOpcEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuOpcEliminarMouseClicked
        // TODO add your handling code here:
       goEliminar();
    }//GEN-LAST:event_menuOpcEliminarMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu1MouseClicked

    public void añadirProblema(String problem) {


    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingreso_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingreso_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingreso_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingreso_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingreso_View().setVisible(true);
            }
        });
    }

    private void EnterObjectPanel(JPanel p) {
        //p.setBackground( new Color(153,153,255));
        p.setBorder(bordePanelbtn);

    }

    private void ExitObjectPanel(JPanel p) {
        //  p.setBackground( new Color(255,255,255));
        p.setBorder(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Intro;
    private javax.swing.JButton btOk;
    private javax.swing.JButton btnGeneratePdf;
    private javax.swing.JButton btnModificacion;
    private javax.swing.JButton btnVer;
    private javax.swing.JComboBox<String> cbBusquedaPor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable2;
    private javax.swing.JMenuBar jmMeniMain;
    private javax.swing.JLabel lbAplicacion;
    private javax.swing.JLabel lbAplication;
    private javax.swing.JLabel lbBtnGuardar;
    private javax.swing.JLabel lbBtnMasProblema;
    private javax.swing.JLabel lbBtnMasSolcion;
    private javax.swing.JLabel lbBtnMasSolucionPerfect;
    private javax.swing.JLabel lbBuscar;
    private javax.swing.JLabel lbDatosTema;
    private javax.swing.JLabel lbErrorAlLlenar;
    private javax.swing.JLabel lbIsModify;
    private javax.swing.JLabel lbNamePanelForThree;
    private javax.swing.JLabel lbNewTema;
    private javax.swing.JLabel lbPrecautionModify;
    private javax.swing.JLabel lbReturn;
    private javax.swing.JLabel lbService;
    private javax.swing.JLabel lbServicio;
    private javax.swing.JLabel lbTema;
    private javax.swing.JLabel lbTema1;
    private javax.swing.JMenu menuOpcEliminar;
    private javax.swing.JMenu menuOpcModificar;
    private javax.swing.JMenu menuOpcNuevo;
    private javax.swing.JPanel pnConsultar;
    private javax.swing.JPanel pnDelete;
    private javax.swing.JPanel pnElinimarBtn;
    private javax.swing.JPanel pnExitBtn;
    private javax.swing.JPanel pnFather;
    private javax.swing.JPanel pnInsertar;
    private javax.swing.JPanel pnModify;
    private javax.swing.JPanel pnModifyBtn;
    private javax.swing.JPanel pnNewSubject;
    private javax.swing.JPanel pnNewSubjectBtn;
    private javax.swing.JPanel pnNewSubjectCard;
    private javax.swing.JPanel pnNewSubjectList;
    private javax.swing.JPanel pnSoporteMainMenu;
    private rspanelgradiente.RSPanelGradiente rSPanelGradiente1;
    private javax.swing.JTable tbModify;
    private javax.swing.JTable tbProblemasSubject;
    private javax.swing.JTable tbSolucionPerfect;
    private javax.swing.JTable tbSolucionSubject;
    private javax.swing.JTextField txtAplicacion;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtNumIndextb;
    private javax.swing.JTextField txtServicio;
    private javax.swing.JTextField txtTema;
    private javax.swing.JTextArea txtaDescription;
    // End of variables declaration//GEN-END:variables
}
