/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_iso.View;

import java.util.List;

/**
 *
 * @author FZ1891
 */
public class LookTema extends javax.swing.JDialog {

    /**
     * Creates new form LookTema
     */
    List lsubject, lProblem, lSolutionAplicada, lSolutionPerfect;
    public LookTema(java.awt.Frame parent, boolean modal,List lsubject,List lProblem,List lSolutionAplicada,List lSolutionPerfect) {
        super(parent, modal);
        initComponents();
        this.lsubject=lsubject;
        this.lProblem=lProblem;
        this.lSolutionAplicada=lSolutionAplicada;
        this.lSolutionPerfect=lSolutionPerfect;
        txtaSubject.setLineWrap(true);
        CleanTxtAreas();
        generateLook();
        generateProblem();
        generateSolucionesAplicadas();
        generatePerfectas();
    }

    void CleanTxtAreas()
    {
        txtaSubject.setText(null);
        txtaProblem.setText(null);
        txtaSolucionesAplicadas.setText(null);
        txtaSolucionesPerfectas.setText(null);
    }       
         
    void generateLook()
    {
        
          txtaSubject.setText("Tema : "+lsubject.get(1).toString()+"\n"
           +"Aplicacion : "+lsubject.get(2).toString()+"\n"+"Servicio : "+lsubject.get(3).toString()
          +"\n"+"Codigo : "+lsubject.get(0).toString());      
    }
    
    void generateProblem()
    {
        String add="";
        for (int i = 0; i < lProblem.size(); i++) 
        {
          add+=lProblem.get(i)+"\n";
        }
        txtaProblem.setText(add);
    }
     void generateSolucionesAplicadas()
    {
        String add="";
        for (int i = 0; i < lSolutionAplicada.size(); i++) 
        {
          add+=lSolutionAplicada.get(i)+"\n";
        }
        txtaSolucionesAplicadas.setText(add);
    }
      void generatePerfectas()
    {
        String add="";
        for (int i = 0; i < lSolutionPerfect.size(); i++) 
        {
          add+=lSolutionPerfect.get(i)+"\n";
        }
        txtaSolucionesPerfectas.setText(add);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
//    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Panel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaSubject = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtaProblem = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtaSolucionesAplicadas = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtaSolucionesPerfectas = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Panel1.setBackground(new java.awt.Color(255, 255, 255));

        txtaSubject.setColumns(20);
        txtaSubject.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        txtaSubject.setRows(5);
        jScrollPane2.setViewportView(txtaSubject);

        txtaProblem.setColumns(20);
        txtaProblem.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        txtaProblem.setRows(5);
        jScrollPane3.setViewportView(txtaProblem);

        jLabel1.setText("PROBLEMAS");

        txtaSolucionesAplicadas.setColumns(20);
        txtaSolucionesAplicadas.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        txtaSolucionesAplicadas.setRows(5);
        jScrollPane4.setViewportView(txtaSolucionesAplicadas);

        jLabel2.setText("SOLUCIONES APLICADAS");

        txtaSolucionesPerfectas.setColumns(20);
        txtaSolucionesPerfectas.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        txtaSolucionesPerfectas.setRows(5);
        jScrollPane6.setViewportView(txtaSolucionesPerfectas);

        jLabel4.setText("SOLUCIONES PERFECTAS");

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
            .addComponent(jScrollPane3)
            .addComponent(jScrollPane4)
            .addComponent(jScrollPane6)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(Panel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LookTema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LookTema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LookTema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LookTema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                LookTema dialog = new LookTema(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea txtaProblem;
    private javax.swing.JTextArea txtaSolucionesAplicadas;
    private javax.swing.JTextArea txtaSolucionesPerfectas;
    private javax.swing.JTextArea txtaSubject;
    // End of variables declaration//GEN-END:variables
}
